name: Build Packages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set environment variables
        run: |
          echo "SWAG_VERSION=$(curl -s 'https://api.linuxserver.io/api/v1/images?include_config=false&include_deprecated=false' | jq -r '.data.repositories.linuxserver | .[] | select(.name == "swag") | .version'") >> $GITHUB_ENV
          echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ghcr.io/jgigantino31/swag:latest, ghcr.io/jgigantino31/swag:${{ env.SWAG_VERSION }}, ghcr.io/jgigantino31/swag:${{ env.DATE }}
