name: Update Check

on:
  schedule:
    - cron:  '24 5 * * *'

jobs:

  check:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      actions: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if base image has been updated
        id: check
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: ghcr.io/linuxserver/swag:latest
          image: ghcr.io/jgigantino31/swag:latest
          platforms: linux/amd64,linux/arm64
      - name: Invoke build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-packages.yaml
        if: steps.check.outputs.needs-updating == 'true'

  keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Keep scheduled workflow alive
        uses: liskin/gh-workflow-keepalive@v1
